# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 959960d1a61b505b7e4abe4098334dccca555ed7a33d955e595f997da11c8cc6a174004bde6dbf3a29eb7549dd3a2d8952d76ef2a58c6bd428cd35b6c5c95c3d

test:
  secret_key_base: 6fa5691041e17aff62beea555e2e5916deadc17088151aeb01b100f0a27e64f5cad859bd005e8bc078a7c9ed703ea55704123fd557258e82df87eadad2c0603b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
